### ISSUE TITLE
proxy-server panic when setting `--proxy-strategies=destHost`.

### ISSUE THREAD

**Issue by xuezhaojun** [kubernetes-sigs/apiserver-network-proxy#513]
The panic error msg:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15e4a2d]
goroutine 56 [running]:
sigs.k8s.io/apiserver-network-proxy/pkg/server.(*ProxyServer).readBackendToChannel(0xc000510f20?, {0x0, 0x0}, 0x17b5a80?, 0x290f070?)
/go/src/github.com/stolostron/cluster-proxy-addon/_output/apiserver-network-proxy/pkg/server/server.go:853 +0x6d
sigs.k8s.io/apiserver-network-proxy/pkg/server.(*ProxyServer).Connect.func3({0x1c72db8, 0xc00068f2c0})
/go/src/github.com/stolostron/cluster-proxy-addon/_output/apiserver-network-proxy/pkg/server/server.go:846 +0x2d
runtime/pprof.Do({0x1c72d48?, 0xc000046050?}, {{0xc0006201c0?, 0x0?, 0x0?}}, 0xc00068f260)
/usr/local/go/src/runtime/pprof/runtime.go:40 +0xa3
created by sigs.k8s.io/apiserver-network-proxy/pkg/server.(*ProxyServer).Connect
/go/src/github.com/stolostron/cluster-proxy-addon/_output/apiserver-network-proxy/pkg/server/server.go:846 +0xc85
```

The root cause is this function, when `--proxy-strategies=destHost` the return value `backend` is nil:  https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/9c1359e68b932458a07464bc607f61a06e879ff3/pkg/server/server.go#L258

```go
func (s *ProxyServer) addBackend(agentID string, conn agent.AgentService_ConnectServer) (backend Backend) {
	for i := 0; i < len(s.BackendManagers); i++ {
		switch s.BackendManagers[i].(type) {
		case *DestHostBackendManager:
			agentIdentifiers, err := getAgentIdentifiers(conn)
			if err != nil {
				klog.ErrorS(err, "fail to get the agent identifiers", "agentID", agentID)
				break
			}
			for _, ipv4 := range agentIdentifiers.IPv4 {
				klog.V(5).InfoS("Add the agent to DestHostBackendManager", "agent address", ipv4)
				s.BackendManagers[i].AddBackend(ipv4, header.IPv4, conn)
			}
			for _, ipv6 := range agentIdentifiers.IPv6 {
				klog.V(5).InfoS("Add the agent to DestHostBackendManager", "agent address", ipv6)
				s.BackendManagers[i].AddBackend(ipv6, header.IPv6, conn)
			}
			for _, host := range agentIdentifiers.Host {
				klog.V(5).InfoS("Add the agent to DestHostBackendManager", "agent address", host)
				s.BackendManagers[i].AddBackend(host, header.Host, conn)
			}
		case *DefaultRouteBackendManager:
			agentIdentifiers, err := getAgentIdentifiers(conn)
			if err != nil {
				klog.ErrorS(err, "fail to get the agent identifiers", "agentID", agentID)
				break
			}
			if agentIdentifiers.DefaultRoute {
				klog.V(5).InfoS("Add the agent to DefaultRouteBackendManager", "agentID", agentID)
				backend = s.BackendManagers[i].AddBackend(agentID, header.DefaultRoute, conn)
			}
		default:
			klog.V(5).InfoS("Add the agent to DefaultBackendManager", "agentID", agentID)
			backend = s.BackendManagers[i].AddBackend(agentID, header.UID, conn)
		}
	}
	return
}
```

But the issue is introduced since this PR: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/463, started by this PR, it uses the `backend.Recv()` instead of `stream.Recv()`.

**Comment by jkh52** [comment]
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/514 is merged.
